name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf ~/microsaas-backend
            mkdir ~/microsaas-backend
            cd ~/microsaas-backend
            git clone https://github.com/juan-dev-hub/project-henry-ford.git .
            docker stop microsaas || true
            docker rm microsaas || true
            docker build -t microsaas .
            docker run -d --name microsaas -p 8080:8080 microsaas
